/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A typed authorization-evidence binding bound into the signed request preimage
 * (bind-not-interpret). Built through the AUDITED `mcps-client-core` providers so the
 * digest is computed in one place — never a caller-supplied magic constant.
 */
export declare class AuthorizationBinding {
  /**
   * `opaque-bytes`: bind the EXACT decoded authorization-artifact bytes (e.g. a
   * bearer token / capability already base64url-decoded off the transport). The
   * digest is `base64url-no-pad(SHA-256(bytes))`, computed by the audited
   * `OpaqueBytesProvider` — not passed in.
   */
  static opaqueBytes(artifactBytes: Buffer): AuthorizationBinding
  /**
   * `authz-system-reference`: bind an external authorization system's self-contained
   * `digestValue` plus its cross-audit reference. The digest is produced by the
   * authz system (the SDK binds, never interprets it).
   */
  static authzSystemReference(authorizationSystemId: string, referenceSchemeId: string, referenceValue: string, digestValue: string): AuthorizationBinding
  /** The base-form tag (`opaque-bytes` / `authz-system-reference`). */
  get bindingType(): string
  get digestAlg(): string
  get digestValue(): string
  /** The authz-system namespace (reference form only; null for opaque-bytes). */
  get authorizationSystemId(): string | null
  /** The authz-system reference handle (reference form only). */
  get referenceValue(): string | null
}

/**
 * Per-route policy: which authorization-binding base forms a route permits (mirrors
 * `mcps-client-core::authz::AuthorizationBindingPolicy`). A binding of a non-permitted
 * type fails closed with `mcps.authorization_binding_type_unsupported`.
 */
export declare class AuthorizationBindingPolicy {
  /** Permit both base forms (the common v0.6 default). */
  static bothBaseForms(): AuthorizationBindingPolicy
  /** Permit only `opaque-bytes`. */
  static opaqueOnly(): AuthorizationBindingPolicy
  /** Permit only `authz-system-reference`. */
  static referenceOnly(): AuthorizationBindingPolicy
  /** A deliberately closed route: permit nothing (every binding is rejected). */
  static closed(): AuthorizationBindingPolicy
  /** Whether this policy permits `binding`'s base form. */
  permits(binding: AuthorizationBinding): boolean
  /**
   * Fail closed (`mcps.authorization_binding_type_unsupported`) if `binding`'s base
   * form is not permitted on this route; otherwise return.
   */
  enforce(binding: AuthorizationBinding): void
}

/**
 * Per-outstanding-request correlation store: binds an outgoing signed request to
 * exactly one acceptable returning response, with nonce-reuse prevention and an
 * expiry sweep. The clock is the caller's: every method takes `nowUnix`. Failures
 * (duplicate id, nonce reuse, late/uncorrelatable, expired) throw an `Error` carrying
 * the frozen `mcps.*` wire code.
 */
export declare class CorrelationStore {
  constructor()
  /** The number of currently-outstanding requests. */
  get outstanding(): number
  /**
   * Register an outstanding request at `nowUnix`. Fails closed on a duplicate
   * correlation id or a nonce still within a prior use's window.
   */
  register(options: RegisterOptions): void
  /**
   * Correlate an incoming response by `correlationId` at `nowUnix`, removing and
   * returning the pending entry (cleanup-on-completion). A late/uncorrelatable or
   * past-deadline response fails closed.
   */
  takeForResponse(correlationId: string, nowUnix: number): PendingRequest
  /**
   * Read an outstanding request's state WITHOUT consuming it (same existence +
   * deadline gate as `takeForResponse`). The multi-round-trip flow peeks the
   * expected `requestHash` before classifying a response as terminal vs
   * `InputRequiredResult`, then consumes via `takeForResponse` (terminal) or
   * `recordInputRequired` (non-terminal).
   */
  peekForResponse(correlationId: string, nowUnix: number): PendingRequest
  /**
   * Correlate a verified, NON-TERMINAL `InputRequiredResult` (ADR-MCPS-047 / D7 —
   * associate-without-consume). Consumes the original response slot but retains the
   * exchange, and returns the continuation binding — pass its two hashes to
   * `signRequest` (`continuationPreviousRequestHash` /
   * `continuationInputRequiredResponseHash`) to sign the answer leg.
   * `inputRequiredResponseHash` is `VerifyResult.responseHash` from the verified
   * elicitation. Fails closed exactly like `takeForResponse`.
   */
  recordInputRequired(correlationId: string, inputRequiredResponseHash: string, nowUnix: number): ContinuationBinding
  /** The number of non-terminal multi-round-trip records awaiting a continuation. */
  get nonTerminalOutstanding(): number
  /** Cancel an outstanding request; returns whether an entry was present. */
  cancel(correlationId: string): boolean
  /** Periodic expiry sweep at `nowUnix`; returns how many pending entries were dropped. */
  sweepExpired(nowUnix: number): number
}

/**
 * A client signing identity (the custody seam). Construct via `Signer.software`
 * (a held-private software key — acceptable in production), `Signer.devFile` (an
 * unprotected dev/test key — rejected under production `require_mcps`), or
 * `Signer.nonExporting` (custody `NonExporting`, the hardening profile — signs via
 * an external device, the only class `SignerPolicy.requireNonExporting` accepts).
 */
export declare class Signer {
  /** In-process software signer (custody class software-held-private). */
  static software(seed: Buffer, signerId: string, keyId: string): Signer
  /** Unprotected dev/test file signer (rejected under production `require_mcps`). */
  static devFile(seed: Buffer, signerId: string, keyId: string): Signer
  /**
   * NON-EXPORTING signer (custody class `NonExporting`, the hardening profile): the
   * key lives in an external device and never enters the SDK. `signCallback` is a
   * callable `(preimage: Buffer) -> base64url-no-pad signature string` (e.g. a
   * `SigningDevice.sign` bound method, or a KMS/HSM client call). This is the only
   * custody class a `requireNonExporting()` policy accepts. Called SYNCHRONOUSLY on
   * the Node main thread during signing.
   */
  static nonExporting(signerId: string, keyId: string, signCallback: (arg: Buffer) => string): Signer
  get signerId(): string
  get keyId(): string
  get custody(): string
}

/**
 * The signer-custody policy for a route/identity (resolved from explicit config).
 * Builder methods return a NEW policy: `new SignerPolicy(...).revokeKeyId(...)`.
 */
export declare class SignerPolicy {
  /** Bind `expectedSigner` for `environment` ("production" | "dev-test") and mode. */
  constructor(expectedSigner: string, environment: string, requireMcps: boolean)
  /** A copy with `keyId` marked revoked (signing through it fails closed). */
  revokeKeyId(keyId: string): SignerPolicy
  /** A copy requiring the hardening profile (only non-exporting custody accepted). */
  requireNonExporting(): SignerPolicy
}

/**
 * A signing device that ENCAPSULATES a key: it holds the private key internally and
 * exposes ONLY a sign operation — there is no getter, so the key can never be read
 * back out. This is the HSM/KMS stand-in for the non-exporting custody path:
 * provision it (here from a seed; in production it wraps a device/KMS handle) and
 * hand its `sign` to `Signer.nonExporting`. The Ed25519 signing is the audited core
 * path (a `SoftwareSigner` held privately, scrubbed on drop).
 */
export declare class SigningDevice {
  /**
   * Provision a device holding the key derived from `seed` (32 bytes). The seed is
   * consumed into the device and never exposed again — modelling key provisioning
   * into hardware. A real deployment constructs the device from a KMS/HSM handle.
   */
  static fromSeed(seed: Buffer, signerId: string, keyId: string): SigningDevice
  /**
   * The device signing operation: Ed25519-sign `preimage` with the device-held key,
   * returning the base64url-no-pad signature. The key never leaves the device.
   */
  sign(preimage: Buffer): string
}

/**
 * The client's trust anchor set for response verification — maps a verified
 * `(server_signer, key_id)` to the PUBLIC verifying key. Response verification
 * consumes public keys only; a verifier never needs private signing material.
 */
export declare class TrustResolver {
  constructor()
  /**
   * Register a server signer by its raw 32-byte Ed25519 PUBLIC key. This is the real
   * verifier input.
   */
  insertPublicKey(signerId: string, keyId: string, publicKey: Buffer): void
  /**
   * DEV/TEST ONLY: register a server signer from a 32-byte SEED, deriving the public
   * key. This exists solely to make parity vectors byte-identical with the signing
   * side — verifiers NEVER need private material; production trust config uses
   * `insertPublicKey`.
   */
  insertDevSeed(signerId: string, keyId: string, seed: Buffer): void
}

/** The canonicalization id of the signed preimage the SDK reproduces exactly. */
export declare function canonicalizationId(): string

/**
 * The continuation binding returned by `recordInputRequired` — feed both hashes to
 * `signRequest` (`continuationPreviousRequestHash` / `continuationInputRequiredResponseHash`)
 * to sign the answer leg (ADR-MCPS-047).
 */
export interface ContinuationBinding {
  previousRequestHash: string
  inputRequiredResponseHash: string
}

/** The MCP-S protocol version this core verifies/signs against (draft-02). */
export declare function coreVersion(): string

/**
 * One outstanding request's retained state, returned by
 * `CorrelationStore.takeForResponse` / `peekForResponse`.
 */
export interface PendingRequest {
  correlationId: string
  requestHash: string
  nonce: string
  issuedAtUnix: number
  deadlineUnix: number
  routeId: string
  audience: string
  expectedServerSigners: Array<string>
  version: string
  canonicalizationId: string
  authzDigest: string
}

/** The named (keyword-style) options for `CorrelationStore.register`. */
export interface RegisterOptions {
  correlationId: string
  requestHash: string
  nonce: string
  deadlineUnix: number
  nowUnix: number
  issuedAtUnix?: number
  routeId?: string
  audience?: string
  expectedServerSigners?: Array<string>
  version?: string
  canonicalizationId?: string
  authzDigest?: string
}

/**
 * The `params._meta` / `result._meta` key under which the MCP-S response envelope
 * lives — the adapter strips it before handing a plain response up to the app.
 */
export declare function responseMetaKey(): string

/**
 * A signed draft-02 request crossing the binding: the exact wire bytes plus the
 * `request_hash` that binds the eventual response. Mirrors the Rust `SignedRequest`.
 */
export interface SignedRequest {
  /** The exact JSON-RPC wire bytes to send (canonical signed preimage + signature). */
  wireBytes: Buffer
  /** `sha256:<b64url-no-pad>` of the signed preimage — hold it to bind the response. */
  requestHash: string
}

/**
 * Sign an ordinary MCP request into a draft-02 MCP-S request via the audited
 * `mcps-client-core`, using a raw 32-byte Ed25519 seed (DEV/TEST custody only — no
 * policy gate). For the production custody gate use `signRequestWithSigner`.
 */
export declare function signRequest(idJson: string, method: string, paramsJson: string, options: SignRequestOptions, authorizationBinding?: AuthorizationBinding | undefined | null): SignedRequest

/**
 * The named (keyword-style) options for `signRequest` — mirrors the Python binding's
 * keyword-only arguments. Exactly one authorization form must be supplied: either
 * `authorizationBinding` (a provider-built `AuthorizationBinding`, the real path) or
 * the raw `bindingDigestAlg`/`bindingDigestValue` opaque shortcut (dev/test).
 */
export interface SignRequestOptions {
  signer: string
  keyId: string
  onBehalfOf: string
  audience: string
  nonce: string
  issuedAt: string
  expiresAt: string
  seed: Buffer
  bindingDigestAlg?: string
  bindingDigestValue?: string
  continuationPreviousRequestHash?: string
  continuationInputRequiredResponseHash?: string
}

/**
 * Sign through a `Signer` gated by a `SignerPolicy` — the production custody path
 * (`build_signed_request_with_signer`). Authorizes the signer (identity, revocation,
 * hardening, dev-file-in-production) BEFORE signing and binds the evidence to the
 * signer's actual identity; a custody failure throws.
 */
export declare function signRequestWithSigner(idJson: string, method: string, paramsJson: string, options: SignWithSignerOptions, signer: Signer, policy: SignerPolicy, authorizationBinding?: AuthorizationBinding | undefined | null): SignedRequest

/**
 * The named options for `signRequestWithSigner` (signer + policy are passed as class
 * arguments; identity comes from the signer, not these options).
 */
export interface SignWithSignerOptions {
  onBehalfOf: string
  audience: string
  nonce: string
  issuedAt: string
  expiresAt: string
  bindingDigestAlg?: string
  bindingDigestValue?: string
  continuationPreviousRequestHash?: string
  continuationInputRequiredResponseHash?: string
}

/**
 * Verify a signed draft-02 response and apply the enforcement decision — the proxy's
 * return-leg pipeline (`verify_signed_response` -> `classify_response_result` ->
 * `decide` -> `audit_for_decision`). Returns a `VerifyResult`; a fail-closed
 * verification is reported there (not thrown). Malformed arguments throw.
 */
export declare function verifyResponse(rawBytes: Buffer, resolver: TrustResolver, options: VerifyResponseOptions): VerifyResult

/** The named options for `verifyResponse` (mirrors Python's keyword arguments). */
export interface VerifyResponseOptions {
  expectedRequestHash: string
  expectedCanonicalizationId?: string
  expectedServerSigner?: string
  /** "require_mcps" (default) | "allow_legacy_explicit". */
  enforcementMode?: string
  legacyAllowed?: boolean
}

/**
 * The structured outcome of `verifyResponse`: the enforcement decision plus the
 * audit-facing path/outcome/reason and (on a verified exchange) the server identity
 * and bound `requestHash`. A fail-closed verification is a RESULT here (with the
 * frozen `mcps.*` wire reason), not a thrown error.
 */
export interface VerifyResult {
  /** "accept" | "fallback" | "fail-closed". */
  decision: string
  /** "mcps-verified" | "legacy-explicit". */
  path: string
  /** "accepted" | "fell-back" | "rejected". */
  outcome: string
  /** Frozen `McpsError::wire_code()` token on a fail-closed rejection; else null. */
  reason?: string
  /** The absence reason that made a legacy fallback eligible (local); else null. */
  legacyReason?: string
  /** The verified server signer (on a verified exchange); else null. */
  serverSigner?: string
  /** The key id that verified the response (on a verified exchange); else null. */
  keyId?: string
  /** The bound `request_hash` (on a verified exchange); else null. */
  requestHash?: string
  /** Convenience: true iff the decision was AcceptMcps. */
  accepted: boolean
  /**
   * ADR-MCPS-047 classification of the SIGNED result body: "terminal" or
   * "input_required". Read only from verified bytes; "terminal" when unverified.
   */
  resultClass: string
  /**
   * The verified response preimage hash (`sha256:<b64url>`) on a verified exchange;
   * else null. When `resultClass === "input_required"` this is the
   * `continuationInputRequiredResponseHash` to pass to `signRequest` for the answer
   * leg (with the original `requestHash` as the previous hash).
   */
  responseHash?: string
  /** Convenience: true iff `resultClass === "input_required"`. */
  inputRequired: boolean
}
