//! Emit the frozen wire codes for each correlation failure, from
//! `CorrelationError::to_mcps_error().wire_code()` — so the Python correlation
//! tests assert the exact codes without hard-coding them.
//!
//!   cargo run --example gen_correlation_vectors > tests/fixtures/correlation_wire_codes.json

use mcps_client_core::CorrelationError;
use serde_json::json;

fn main() {
    let fixture = json!({
        "_comment": "Frozen wire codes for CorrelationError variants (MCPS-48 mapping). \
                     Generated by `cargo run --example gen_correlation_vectors`. Do not edit.",
        "duplicate_correlation_id": CorrelationError::DuplicateCorrelationId.to_mcps_error().wire_code(),
        "nonce_reuse": CorrelationError::NonceReuse.to_mcps_error().wire_code(),
        "uncorrelatable": CorrelationError::Uncorrelatable.to_mcps_error().wire_code(),
        "expired": CorrelationError::Expired.to_mcps_error().wire_code(),
    });
    println!("{}", serde_json::to_string_pretty(&fixture).unwrap());
}
