//! Generate the parity golden vector for the Python `sign_request` binding.
//!
//! Independent oracle: builds the signed request via `mcps-client-core` directly
//! — the SAME function the proxy uses — and prints the fixture JSON to stdout.
//! The Python parity test then asserts the binding reproduces it byte for byte.
//!
//!   cargo run --example gen_vector > tests/fixtures/sign_request_vector.json

use mcps_client_core::{build_signed_request, RequestSigningInputs};
use mcps_core::{AuthorizationBinding, SigningKey};
use serde_json::{json, Map, Value};

fn main() {
    // Canonical inputs (the single source of truth — the Python test reads these
    // back out of the fixture and feeds them to the binding).
    let id_json = "\"req-1\"";
    let method = "tools/call";
    let params_json = r#"{"name":"echo","arguments":{"text":"hello"}}"#;
    let signer = "did:example:client";
    let key_id = "client-key-1";
    let on_behalf_of = "user:alice";
    let audience = "did:example:server";
    let binding_digest_alg = "sha256";
    let binding_digest_value = "RBNvo1WzZ4oRRq0W9-hknpT7T8If536DEMBg9hyq_4o";
    let nonce = "Zm9vYmFyYmF6cXV4MTIzNDU2Nzg5MA";
    let issued_at = "2026-06-30T20:00:00Z";
    let expires_at = "2026-06-30T20:05:00Z";
    let seed: [u8; 32] = [42u8; 32];

    // Parse exactly as the binding does, so the oracle and the binding agree on
    // how id/params are interpreted.
    let id: Value = serde_json::from_str(id_json).unwrap();
    let params: Map<String, Value> = serde_json::from_str(params_json).unwrap();
    let binding = AuthorizationBinding::OpaqueBytes {
        digest_alg: binding_digest_alg.to_string(),
        digest_value: binding_digest_value.to_string(),
    };
    let inputs = RequestSigningInputs::with_default_canonicalization(
        signer,
        key_id,
        on_behalf_of,
        audience,
        binding,
        nonce,
        issued_at,
        expires_at,
    );
    let key = SigningKey::from_seed_bytes(&seed);
    let signed = build_signed_request(&id, method, params, &inputs, &key).unwrap();

    // wire_bytes is serialized JSON (valid UTF-8) — store it as text so the fixture
    // is human-readable and the Python test compares decoded strings.
    let wire = String::from_utf8(signed.wire_bytes().to_vec()).unwrap();
    let seed_hex: String = seed.iter().map(|b| format!("{b:02x}")).collect();

    let fixture = json!({
        "_comment": "Golden vector for the Python sign_request binding. Generated by \
                     `cargo run --example gen_vector` from mcps-client-core (independent \
                     oracle; same path the proxy uses). Do not edit by hand.",
        "inputs": {
            "id_json": id_json,
            "method": method,
            "params_json": params_json,
            "signer": signer,
            "key_id": key_id,
            "on_behalf_of": on_behalf_of,
            "audience": audience,
            "binding_digest_alg": binding_digest_alg,
            "binding_digest_value": binding_digest_value,
            "nonce": nonce,
            "issued_at": issued_at,
            "expires_at": expires_at,
            "seed_hex": seed_hex,
        },
        "expected_request_hash": signed.request_hash(),
        "expected_wire_bytes": wire,
    });
    println!("{}", serde_json::to_string_pretty(&fixture).unwrap());
}
