"""Parity tests — the acceptance gate for issue #199 ("parity tests vs proxy").

The Python SDK MUST produce a byte-identical signed request to the Rust path for
the same input. Byte parity is the whole point of binding to ``mcps-client-core``
instead of reimplementing it.

``tests/fixtures/sign_request_vector.json`` is the golden vector, generated by the
independent Rust oracle (``cargo run --example gen_vector`` → ``mcps-client-core``,
the same construction the proxy uses). The parity test feeds the fixture's inputs
to the Python binding and asserts the wire bytes + request_hash match exactly.

Regenerate the fixture after any envelope/canonicalization change::

    cargo run --example gen_vector > tests/fixtures/sign_request_vector.json
"""

import json
from pathlib import Path

import pytest

import mcps_sdk

FIXTURE = Path(__file__).parent / "fixtures" / "sign_request_vector.json"


def _load_vector():
    return json.loads(FIXTURE.read_text())


def test_core_link():
    """Smoke test: the native core is reachable and reports protocol constants.

    Proves the PyO3 link to mcps-client-core / mcps-core works end to end.
    """
    version = mcps_sdk.core_version()
    assert isinstance(version, str) and version, "core_version() should be non-empty"
    assert isinstance(mcps_sdk.canonicalization_id(), str)


def _sign_from_fixture(inp):
    return mcps_sdk.sign_request(
        inp["id_json"],
        inp["method"],
        inp["params_json"],
        signer=inp["signer"],
        key_id=inp["key_id"],
        on_behalf_of=inp["on_behalf_of"],
        audience=inp["audience"],
        binding_digest_alg=inp["binding_digest_alg"],
        binding_digest_value=inp["binding_digest_value"],
        nonce=inp["nonce"],
        issued_at=inp["issued_at"],
        expires_at=inp["expires_at"],
        seed=bytes.fromhex(inp["seed_hex"]),
    )


def test_signed_request_bytes_match_proxy():
    """Same inputs -> identical wire_bytes() as the mcps-client-core oracle.

    This guards the PyO3 boundary: the binding must marshal id/params/binding/seed
    and return the exact bytes the audited Rust core produced.
    """
    vector = _load_vector()
    signed = _sign_from_fixture(vector["inputs"])

    assert signed.wire_bytes.decode() == vector["expected_wire_bytes"]
    assert signed.request_hash == vector["expected_request_hash"]


def test_request_hash_well_formed():
    """request_hash is the documented `sha256:<b64url-no-pad>` shape."""
    signed = _sign_from_fixture(_load_vector()["inputs"])
    assert signed.request_hash.startswith("sha256:")
    assert "=" not in signed.request_hash  # b64url no-pad


def test_signature_value_does_not_change_request_hash():
    """request_hash is computed over the preimage (signature.value excluded), so a
    second identical signing yields the same hash and bytes — determinism."""
    inp = _load_vector()["inputs"]
    a = _sign_from_fixture(inp)
    b = _sign_from_fixture(inp)
    assert a.wire_bytes == b.wire_bytes
    assert a.request_hash == b.request_hash


def test_bad_seed_length_is_rejected():
    """A seed that is not 32 bytes fails closed with a clear error (no signing)."""
    inp = dict(_load_vector()["inputs"])
    with pytest.raises(ValueError, match="seed must be exactly 32 bytes"):
        mcps_sdk.sign_request(
            inp["id_json"],
            inp["method"],
            inp["params_json"],
            signer=inp["signer"],
            key_id=inp["key_id"],
            on_behalf_of=inp["on_behalf_of"],
            audience=inp["audience"],
            binding_digest_alg=inp["binding_digest_alg"],
            binding_digest_value=inp["binding_digest_value"],
            nonce=inp["nonce"],
            issued_at=inp["issued_at"],
            expires_at=inp["expires_at"],
            seed=b"\x00" * 16,
        )


@pytest.mark.skip(reason="scaffold: response verification binding not implemented (#199)")
def test_response_verification_matches_proxy():
    """Same signed response + trust resolver -> identical EnforcementDecision /
    audit path (McpsVerified vs LegacyExplicit vs FailClosed) as the proxy."""
