/**
 * Shared oracle fixtures — the SINGLE source of truth for byte-parity.
 *
 * The golden vectors are generated by the independent Rust oracle (`cargo run
 * --example gen_vector` / `gen_response_vector` / `gen_correlation_vectors` in
 * `mcps-client-core`, the same construction the proxy uses). They are language-agnostic
 * JSON, so the TypeScript SDK consumes the EXACT same files the Python SDK's parity
 * tests do — a drift in either binding is caught against the same oracle.
 *
 * Regenerate after any envelope/canonicalization change (from the repo root):
 *   cargo run --example gen_vector > sdk/python/tests/fixtures/sign_request_vector.json
 *   cargo run --example gen_response_vector > sdk/python/tests/fixtures/verify_response_vectors.json
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";

const FIXTURE_DIR = join(__dirname, "..", "..", "python", "tests", "fixtures");

function load<T>(name: string): T {
  return JSON.parse(readFileSync(join(FIXTURE_DIR, name), "utf-8")) as T;
}

export interface SignVector {
  expected_request_hash: string;
  expected_wire_bytes: string;
  inputs: {
    audience: string;
    binding_digest_alg: string;
    binding_digest_value: string;
    expires_at: string;
    id_json: string;
    issued_at: string;
    key_id: string;
    method: string;
    nonce: string;
    on_behalf_of: string;
    params_json: string;
    seed_hex: string;
    signer: string;
  };
}

export interface ResponseScenario {
  name: string;
  response_bytes: string;
  params: {
    expected_request_hash: string;
    expected_canonicalization_id: string | null;
    expected_server_signer: string | null;
    enforcement_mode: string;
    legacy_allowed: boolean;
  };
  expected: {
    decision: string;
    path: string;
    outcome: string;
    reason: string | null;
    server_signer: string | null;
    key_id: string | null;
    request_hash: string | null;
    accepted: boolean;
    response_hash?: string;
  };
}

export interface ResponseVectors {
  client_request_hash: string;
  server: { signer_id: string; key_id: string; public_key_hex: string; seed_hex: string };
  scenarios: ResponseScenario[];
}

export const SIGN_VECTOR = load<SignVector>("sign_request_vector.json");
export const RESPONSE_VECTORS = load<ResponseVectors>("verify_response_vectors.json");
export const CORRELATION_CODES = load<Record<string, string>>("correlation_wire_codes.json");

export function scenario(name: string): ResponseScenario {
  const s = RESPONSE_VECTORS.scenarios.find((x) => x.name === name);
  if (!s) throw new Error(`no scenario named ${name}`);
  return s;
}
